# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/actual"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/beszel-agent"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/beszel"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/glance"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/homeassistant"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/nginx"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/pihole"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/portainer"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/speedtest-tracker"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/unbound"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/watchtower"
    schedule:
      interval: "daily"
