services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=<Check speedtest-tracker docs for APP_KEY generation>
            - DB_CONNECTION=sqlite
            - DISPLAY_TIMEZONE=Asia/Calcutta
            - SPEEDTEST_SCHEDULE="0,30 * * * *"
            - SPEEDTEST_SERVERS=7379,48124
            - PRUNE_RESULTS_OLDER_THAN=7
        healthcheck:
          test: curl -fSs APP_URL/api/healthcheck | jq -r .message || exit 1
          interval: 10s
          retries: 3
          start_period: 30s
          timeout: 10s    
        volumes:
            - ./config:/config
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        networks:
          - pi_net

networks:
  pi_net:
    external: true