services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config # Good! (Remember to create this host directory)
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro # Keep if needed
    ports:
      # This is needed now because we removed 'network_mode: host'
      # Home Assistant will be accessible at http://<your_pi_ip>:8123
      - "8123:8123"
    restart: unless-stopped
    privileged: true 
    environment: # Good to add for consistency and correct time/log handling
      - TZ=Asia/Calcutta # Replace with your actual timezone if different
    networks:
      - pi_net # This ensures Home Assistant is on your shared network

networks:
  pi_net:
    external: true