services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginxo'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - pi_net

networks:
  pi_net:
    external: true
